export const assetFilenames = [
  "tag-logo-light.svg",
  "tag-logo-dark.svg",
  "tag-favicon.png",
  "hero-performance-dashboard.webp",
  "hero-performance-dashboard-mobile.webp",
  "hero-background-texture.webp",
  "client-logo-01.svg",
  "client-logo-02.svg",
  "client-logo-03.svg",
  "client-logo-04.svg",
  "client-logo-05.svg",
  "client-logo-06.svg",
  "client-logo-07.svg",
  "client-logo-08.svg",
  "client-logo-09.svg",
  "client-logo-10.svg",
  "client-logo-11.svg",
  "client-logo-12.svg",
  "service-meta-ads.svg",
  "service-google-ads.svg",
  "service-lead-funnel.svg",
  "service-campaign-audit.svg",
  "service-creative-production.svg",
  "case-study-featured.webp",
  "case-study-metrics-dashboard.webp",
  "industry-real-estate.webp",
  "industry-automobile.webp",
  "industry-education.webp",
  "industry-healthcare.webp",
  "industry-consumer-brand.webp",
  "industry-local-business.webp",
  "tag-agency-team.webp",
  "tag-agency-strategy-session.webp",
  "contact-cta-background.webp"
];

export const missingVerificationItems = [
  "Case study numbers and spend formatting",
  "Approved client logos and permissions",
  "Contact information",
  "Address",
  "Social links",
  "Creative Production service status",
  "Testimonials or case-study permissions",
  "Political organisation logo permissions, if displayed"
];
