export const assetFilenames = [
  "tag-agency-logo-cropped.png",
  "tag-agency-logo.png",
  "meta-business-partner-cropped.png",
  "meta-business-partner.png",
  "hero-header-banner.jpeg",
  "tag-logo-light.svg",
  "tag-logo-dark.svg",
  "tag-favicon.png",
  "hero-performance-dashboard.webp",
  "hero-performance-dashboard-mobile.webp",
  "hero-background-texture.webp",
  "client-logo-01.svg",
  "client-logo-02.svg",
  "client-logo-03.svg",
  "client-logo-04.svg",
  "client-logo-05.svg",
  "client-logo-06.svg",
  "client-logo-07.svg",
  "client-logo-08.svg",
  "client-logo-09.svg",
  "client-logo-10.svg",
  "client-logo-11.svg",
  "client-logo-12.svg",
  "service-meta-ads.svg",
  "service-google-ads.svg",
  "service-lead-funnel.svg",
  "service-campaign-audit.svg",
  "service-creative-production.svg",
  "case-study-featured.webp",
  "case-study-metrics-dashboard.webp",
  "industry-real-estate.webp",
  "industry-automobile.webp",
  "industry-education.webp",
  "industry-healthcare.webp",
  "industry-consumer-brand.webp",
  "industry-local-business.webp",
  "tag-agency-team.webp",
  "tag-agency-strategy-session.webp",
  "contact-cta-background.webp"
];

export const suppliedClientLogoFiles = [
  "client-logo-01.png",
  "client-logo-02.png",
  "client-logo-03.png",
  "client-logo-04.png",
  "client-logo-05.png",
  "client-logo-06.png",
  "client-logo-07.png",
  "client-logo-08.png",
  "client-logo-09.png",
  "client-logo-10.png",
  "client-logo-11.png",
  "client-logo-12.png",
  "client-logo-13.png",
  "client-logo-14.png",
  "client-logo-15.png",
  "client-logo-16.png",
  "client-logo-17.png",
  "client-logo-18.png",
  "client-logo-19.png",
  "client-logo-20.png",
  "client-logo-21.png",
  "client-logo-22.png",
  "client-logo-23.png",
  "client-logo-24.png",
  "client-logo-25.png",
  "client-logo-26.png",
  "client-logo-27.png",
  "client-logo-28.png",
  "client-logo-29.png",
  "client-logo-30.png",
  "client-logo-31.png",
  "client-logo-32.png",
  "client-logo-33.jpg",
  "client-logo-34.png",
  "client-logo-35.png",
  "client-logo-36.png"
];

export const phoneNumber = "7411110987";
export const phoneHref = "tel:+917411110987";
export const whatsAppHref = "https://wa.me/917411110987";

export const missingVerificationItems = [
  "Case study numbers and spend formatting",
  "Approved client logos and permissions",
  "Contact information",
  "Address",
  "Social links",
  "Creative Production service status",
  "Testimonials or case-study permissions",
  "Political organisation logo permissions, if displayed"
];
